name: sprite
version: '${version}'
main: sh.harold.sprite.Sprite
api-version: '1.21'
description: Sprite development tooling commands.
authors:
  - Harold
  - ZECHEESELORD
commands:
  sprite:
    description: Sprite development tooling commands.
    usage: /<command>
    permission: sprite.command
permissions:
  sprite.command:
    description: Access to /sprite commands.
    default: op
